version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vidsummize-app
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JOOQ_SQL_DIALECT: ${SPRING_JOOQ_SQL_DIALECT}
      SERVER_PORT: ${SERVER_PORT}
      YTDLP_COMMAND: yt-dlp
      WHISPER_CPP_PATH: /opt/whisper/whisper.cpp/build/bin/whisper-cli
      WHISPER_MODEL_PATH: /opt/whisper/whisper.cpp/models/ggml-base.en.bin
      WHISPER_WORKDIR: /opt/whisper/whisper.cpp
      OLLAMA_API_URL: http://ollama:11434/api/chat
      OLLAMA_MODEL_NAME: ${OLLAMA_MODEL_NAME}
    depends_on:
      - db
      - ollama
    networks:
      - vidsummize-net

  db:
    image: postgres:15
    container_name: vidsummize-db
    environment:
      POSTGRES_DB: vidsummize
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vidsummize-net

  ollama:
    image: ollama/ollama:latest
    container_name: vidsummize-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/entrypoint.sh" ]
    networks:
      - vidsummize-net

volumes:
  pgdata:

networks:
  vidsummize-net:
