/*
 * This file is generated by jOOQ.
 */
package com.vidsummize.jooq;


import com.vidsummize.jooq.tables.Video;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.video</code>.
     */
    public static final Video VIDEO = Video.VIDEO;
}
