spring:
  application:
    name: vidsummize
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vidsummize}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jooq:
    sql-dialect: ${SPRING_JOOQ_SQL_DIALECT:postgres}

server:
  port: ${SERVER_PORT:8080}