/*
 * This file is generated by jOOQ.
 */
package com.vidsummize.jooq.tables.records;


import com.vidsummize.jooq.tables.Video;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VideoRecord extends UpdatableRecordImpl<VideoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.video.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.video.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.video.youtube_url</code>.
     */
    public void setYoutubeUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.video.youtube_url</code>.
     */
    public String getYoutubeUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.video.transcription</code>.
     */
    public void setTranscription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.video.transcription</code>.
     */
    public String getTranscription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.video.summary</code>.
     */
    public void setSummary(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.video.summary</code>.
     */
    public String getSummary() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.video.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.video.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VideoRecord
     */
    public VideoRecord() {
        super(Video.VIDEO);
    }

    /**
     * Create a detached, initialised VideoRecord
     */
    public VideoRecord(Integer id, String youtubeUrl, String transcription, String summary, LocalDateTime createdAt) {
        super(Video.VIDEO);

        setId(id);
        setYoutubeUrl(youtubeUrl);
        setTranscription(transcription);
        setSummary(summary);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
